import { promises as fs } from 'node:fs'
import { fileURLToPath } from 'node:url'

export const SUPPORTED_EVENTS = ['deploy-building', 'deploy-succeeded', 'deploy-failed']
const RUNTIME_PATH = fileURLToPath(new URL('./runtime.mjs', import.meta.url))

const asList = (value) => (value === undefined || value === null || value === '' ? [] : [].concat(value))

export function resolveConfig(inputs = {}) {
  const events = asList(inputs.events)
  const unknown = events.filter((e) => !SUPPORTED_EVENTS.includes(e))
  if (unknown.length) {
    throw new Error(`Unsupported events: ${unknown.join(', ')}. Supported: ${SUPPORTED_EVENTS.join(', ')}`)
  }
  return {
    events,
    config: {
      contexts: asList(inputs.contexts),
      siteLabel: inputs.siteLabel || null,
      webhookEnvVar: inputs.webhookEnvVar || 'SLACK_WEBHOOK_URL',
      mentionOnFailure: inputs.mentionOnFailure || null,
    },
  }
}

export async function renderFunction(event, config) {
  const runtime = await fs.readFile(RUNTIME_PATH, 'utf8')
  return `${runtime}
// --- generated by netlify-plugin-slack-notify ---
export const handler = createHandler(${JSON.stringify(config)}, ${JSON.stringify(event)})
`
}
