import { promises as fs } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

export const SUPPORTED_EVENTS = ['deploy-building', 'deploy-succeeded', 'deploy-failed']
const RUNTIME_PATH = fileURLToPath(new URL('./runtime.mjs', import.meta.url))

const asList = (value) => (value === undefined || value === null || value === '' ? [] : [].concat(value))

export function resolveConfig(inputs = {}) {
  const events = asList(inputs.events)
  const unknown = events.filter((e) => !SUPPORTED_EVENTS.includes(e))
  if (unknown.length) {
    throw new Error(`Unsupported events: ${unknown.join(', ')}. Supported: ${SUPPORTED_EVENTS.join(', ')}`)
  }
  return {
    events,
    config: {
      contexts: asList(inputs.contexts),
      siteLabel: inputs.siteLabel || null,
      webhookEnvVar: inputs.webhookEnvVar || 'SLACK_WEBHOOK_URL',
      mentionOnFailure: inputs.mentionOnFailure || null,
    },
  }
}

export async function renderFunction(event, config) {
  const runtime = await fs.readFile(RUNTIME_PATH, 'utf8')
  return `${runtime}
// --- generated by netlify-plugin-slack-notify ---
export const handler = createHandler(${JSON.stringify(config)}, ${JSON.stringify(event)})
`
}

// Writes one function per event and hands it to Netlify, skipping any event the
// project already handles with its own function of the same name.
export async function onBuild({ inputs, constants, utils }) {
  let resolved
  try {
    resolved = resolveConfig(inputs)
  } catch (error) {
    return utils.build.failPlugin(error.message)
  }
  const { events, config } = resolved

  const internalDir = constants.INTERNAL_FUNCTIONS_SRC && resolve(constants.INTERNAL_FUNCTIONS_SRC)
  const existing = (await utils.functions.list().catch(() => [])) ?? []
  const userOwned = new Set(
    existing
      .filter((fn) => !internalDir || !resolve(fn.mainFile).startsWith(internalDir + sep))
      .map((fn) => fn.name),
  )

  const outDir = await fs.mkdtemp(join(tmpdir(), 'slack-notify-'))
  const added = []
  for (const event of events) {
    if (userOwned.has(event)) {
      console.log(`[slack-notify] Project defines its own ${event} function; leaving it in place.`)
      continue
    }
    const file = join(outDir, `${event}.mjs`)
    await fs.writeFile(file, await renderFunction(event, config))
    await utils.functions.add(file)
    added.push(event)
  }

  const summary = added.length
    ? `Added ${added.join(', ')} for ${config.contexts.join(', ') || 'all contexts'}`
    : 'No functions added'
  console.log(`[slack-notify] ${summary}`)
  utils.status.show({ title: 'Slack notifications', summary })
}
